// Generated by https://quicktype.io

namespace alma_authorizenet_payment_reporting
{
    using System;
    using Newtonsoft.Json;

    public partial class AlmaFees
    {
        [JsonProperty("fee")]
        public Fee[] Fee { get; set; }

        [JsonProperty("total_record_count")]
        public long TotalRecordCount { get; set; }

        [JsonProperty("total_sum")]
        public double TotalSum { get; set; }

        [JsonProperty("currency")]
        public string Currency { get; set; }
    }

    public partial class Fee
    {
        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("type")]
        public Owner Type { get; set; }

        [JsonProperty("status")]
        public Owner Status { get; set; }

        [JsonProperty("user_primary_id")]
        public Barcode UserPrimaryId { get; set; }

        [JsonProperty("balance")]
        public double Balance { get; set; }

        [JsonProperty("remaining_vat_amount")]
        public double RemainingVatAmount { get; set; }

        [JsonProperty("original_amount")]
        public double OriginalAmount { get; set; }

        [JsonProperty("original_vat_amount")]
        public double OriginalVatAmount { get; set; }

        [JsonProperty("creation_time")]
        public DateTimeOffset CreationTime { get; set; }

        [JsonProperty("status_time")]
        public DateTimeOffset StatusTime { get; set; }

        [JsonProperty("comment")]
        public object Comment { get; set; }

        [JsonProperty("owner")]
        public Owner Owner { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("barcode")]
        public Barcode Barcode { get; set; }

        [JsonProperty("transaction")]
        public Transaction[] Transaction { get; set; }

        [JsonProperty("link")]
        public Uri Link { get; set; }
    }

    public partial class Barcode
    {
        [JsonProperty("value")]
        public string Value { get; set; }

        [JsonProperty("link")]
        public Uri Link { get; set; }
    }

    public partial class Owner
    {
        [JsonProperty("value")]
        public string Value { get; set; }

        [JsonProperty("desc")]
        public string Desc { get; set; }
    }

    public partial class Transaction
    {
        [JsonProperty("type")]
        public Owner Type { get; set; }

        [JsonProperty("amount")]
        public double Amount { get; set; }

        [JsonProperty("vat_amount")]
        public double VatAmount { get; set; }

        [JsonProperty("created_by")]
        public string CreatedBy { get; set; }

        [JsonProperty("external_transaction_id")]
        public string ExternalTransactionId { get; set; }

        [JsonProperty("transaction_time")]
        public DateTimeOffset TransactionTime { get; set; }

        [JsonProperty("received_by")]
        public Owner ReceivedBy { get; set; }

        [JsonProperty("payment_method")]
        public Owner PaymentMethod { get; set; }
    }
}
